// GENERATED from PostEx get-operational-city on 2026-10-01. Run npm run sync:cities to refresh.

export interface CityOption {
  value: string;
  label: string;
}

export const CITIES: readonly CityOption[] = [
  { value: "ABBASPUR", label: "ABBASPUR" },
  { value: "ABBOTTABAD", label: "ABBOTTABAD" },
  { value: "ABDUL HAKEEM", label: "ABDUL HAKEEM" },
  { value: "ADDA JOHAL", label: "ADDA JOHAL" },
  { value: "ADDA ONE R", label: "ADDA ONE R" },
  { value: "ADDA PANWAN", label: "ADDA PANWAN" },
  { value: "Adda Plot", label: "Adda Plot" },
  { value: "ADDA SHAIKH WAHAN", label: "ADDA SHAIKH WAHAN" },
  { value: "ADDA SIRAJ", label: "ADDA SIRAJ" },
  { value: "AHMAD NAGAR CHATHA", label: "AHMAD NAGAR CHATHA" },
  { value: "AHMADAL", label: "AHMADAL" },
  { value: "AHMED NAGAR", label: "AHMED NAGAR" },
  { value: "AHMEDPUR EAST", label: "AHMEDPUR EAST" },
  { value: "AHMEDPUR SIAL", label: "AHMEDPUR SIAL" },
  { value: "AIMANABAD TOWN", label: "AIMANABAD TOWN" },
  { value: "AJNIA WALA", label: "AJNIA WALA" },
  { value: "AKHTAR ABAD", label: "AKHTAR ABAD" },
  { value: "AKORA KHATAK", label: "AKORA KHATAK" },
  { value: "AKWAL", label: "AKWAL" },
  { value: "ALI PUR BANGLA", label: "ALI PUR BANGLA" },
  { value: "ALIPUR", label: "ALIPUR" },
  { value: "ALIPUR CHATHA", label: "ALIPUR CHATHA" },
  { value: "ALLAH ABAD", label: "ALLAH ABAD" },
  { value: "ALMAS", label: "ALMAS" },
  { value: "AMANGARH", label: "AMANGARH" },
  { value: "AMINABAD", label: "AMINABAD" },
  { value: "AMINPUR BANGLA", label: "AMINPUR BANGLA" },
  { value: "AMRA KALAN", label: "AMRA KALAN" },
  { value: "AMRA KHURD", label: "AMRA KHURD" },
  { value: "ANWARABAD", label: "ANWARABAD" },
  { value: "ARIFWALA", label: "ARIFWALA" },
  { value: "ARJA", label: "ARJA" },
  { value: "ASHARAY", label: "ASHARAY" },
  { value: "ATHMUQAM", label: "ATHMUQAM" },
  { value: "ATTOCK", label: "ATTOCK" },
  { value: "ATTOWALA", label: "ATTOWALA" },
  { value: "AYUBIA", label: "AYUBIA" },
  { value: "BADDOMALHI", label: "BADDOMALHI" },
  { value: "BADIN", label: "BADIN" },
  { value: "BAFFA", label: "BAFFA" },
  { value: "BAGH (AJK)", label: "BAGH (AJK)" },
  { value: "BAHAWALNAGAR", label: "BAHAWALNAGAR" },
  { value: "BAHAWALPUR", label: "BAHAWALPUR" },
  { value: "BAHRAIN", label: "BAHRAIN" },
  { value: "Bahria Orchard", label: "Bahria Orchard" },
  { value: "BAHTAR MORE", label: "BAHTAR MORE" },
  { value: "BAIDARA", label: "BAIDARA" },
  { value: "BAIG PUR", label: "BAIG PUR" },
  { value: "BAJAR WALA", label: "BAJAR WALA" },
  { value: "BALAKOT", label: "BALAKOT" },
  { value: "BALAMBAT", label: "BALAMBAT" },
  { value: "BAN BAJWA", label: "BAN BAJWA" },
  { value: "BANDHI", label: "BANDHI" },
  { value: "BANGULDERO", label: "BANGULDERO" },
  { value: "BANNU", label: "BANNU" },
  { value: "BANSRA GALI", label: "BANSRA GALI" },
  { value: "BARA MANGA", label: "BARA MANGA" },
  { value: "BARA MARKET", label: "BARA MARKET" },
  { value: "BARAWAL", label: "BARAWAL" },
  { value: "BARIAN", label: "BARIAN" },
  { value: "BARIKOT", label: "BARIKOT" },
  { value: "BARKHAN", label: "BARKHAN" },
  { value: "BARRTH", label: "BARRTH" },
  { value: "BASHARAT", label: "BASHARAT" },
  { value: "BASIRPUR", label: "BASIRPUR" },
  { value: "BASTI MALOOK", label: "BASTI MALOOK" },
  { value: "BATKHELA", label: "BATKHELA" },
  { value: "BATTAGRAM", label: "BATTAGRAM" },
  { value: "BEGUM KOT", label: "BEGUM KOT" },
  { value: "BEKNANWALA", label: "BEKNANWALA" },
  { value: "BELA", label: "BELA" },
  { value: "Bhagowal Khurd", label: "Bhagowal Khurd" },
  { value: "BHAGTANWALA", label: "BHAGTANWALA" },
  { value: "BHAI PHERU", label: "BHAI PHERU" },
  { value: "BHAKKAR", label: "BHAKKAR" },
  { value: "BHAKNAWALI", label: "BHAKNAWALI" },
  { value: "BHAL SYEDAN", label: "BHAL SYEDAN" },
  { value: "BHALWAAL", label: "BHALWAAL" },
  { value: "BHAN SAYEDABAD", label: "BHAN SAYEDABAD" },
  { value: "BHARA KAHU", label: "BHARA KAHU" },
  { value: "BHAU GHASITPUR", label: "BHAU GHASITPUR" },
  { value: "BHERA", label: "BHERA" },
  { value: "BHIKKI", label: "BHIKKI" },
  { value: "BHIMBER (AJK)", label: "BHIMBER (AJK)" },
  { value: "Bhoe Asal", label: "Bhoe Asal" },
  { value: "BHOMAN BATTH", label: "BHOMAN BATTH" },
  { value: "BHOPALWALA", label: "BHOPALWALA" },
  { value: "BHOWANA", label: "BHOWANA" },
  { value: "BHURBUN (P.C. HOTEL)", label: "BHURBUN (P.C. HOTEL)" },
  { value: "BIBYAWAR", label: "BIBYAWAR" },
  { value: "BILALABAD", label: "BILALABAD" },
  { value: "Birth Both", label: "Birth Both" },
  { value: "BONGA HAYAT", label: "BONGA HAYAT" },
  { value: "BOSAL", label: "BOSAL" },
  { value: "BOZDAR WADA", label: "BOZDAR WADA" },
  { value: "BUCHEKE", label: "BUCHEKE" },
  { value: "BUNER", label: "BUNER" },
  { value: "BUNI", label: "BUNI" },
  { value: "BUREWALA", label: "BUREWALA" },
  { value: "CADET COLLEGE SUNNY BANK", label: "CADET COLLEGE SUNNY BANK" },
  { value: "Canal City", label: "Canal City" },
  { value: "CHAK ALI SHAH", label: "CHAK ALI SHAH" },
  { value: "CHAK BELI KHAN", label: "CHAK BELI KHAN" },
  { value: "CHAK FATEH SHAH", label: "CHAK FATEH SHAH" },
  { value: "CHAK HAMID", label: "CHAK HAMID" },
  { value: "CHAK JANI", label: "CHAK JANI" },
  { value: "CHAK JHUMRA", label: "CHAK JHUMRA" },
  { value: "CHAK PARANA", label: "CHAK PARANA" },
  { value: "CHAK SHADI", label: "CHAK SHADI" },
  { value: "CHAK SWARI (AJK)", label: "CHAK SWARI (AJK)" },
  { value: "CHAKDARA", label: "CHAKDARA" },
  { value: "CHAKLALA", label: "CHAKLALA" },
  { value: "CHAKORI BHILOWAL", label: "CHAKORI BHILOWAL" },
  { value: "CHAKRI", label: "CHAKRI" },
  { value: "CHAKSWARI", label: "CHAKSWARI" },
  { value: "CHAKWAL", label: "CHAKWAL" },
  { value: "CHAMAN", label: "CHAMAN" },
  { value: "CHAMANKOT", label: "CHAMANKOT" },
  { value: "CHANGA MANGA", label: "CHANGA MANGA" },
  { value: "CHANNAN", label: "CHANNAN" },
  { value: "CHAR BAGH", label: "CHAR BAGH" },
  { value: "CHARHOI", label: "CHARHOI" },
  { value: "CHARSADDA", label: "CHARSADDA" },
  { value: "CHASHMA", label: "CHASHMA" },
  { value: "CHAUBARA", label: "CHAUBARA" },
  { value: "CHAWINDA", label: "CHAWINDA" },
  { value: "CHENAB NAGAR", label: "CHENAB NAGAR" },
  { value: "CHIANWALI", label: "CHIANWALI" },
  { value: "CHICHAWATNI", label: "CHICHAWATNI" },
  { value: "CHIKKAR", label: "CHIKKAR" },
  { value: "CHILAS", label: "CHILAS" },
  { value: "CHILLIANWALA", label: "CHILLIANWALA" },
  { value: "CHINIOT", label: "CHINIOT" },
  { value: "CHINJI", label: "CHINJI" },
  { value: "CHISHTIAN", label: "CHISHTIAN" },
  { value: "CHISTIAN", label: "CHISTIAN" },
  { value: "CHITRAL", label: "CHITRAL" },
  { value: "CHITTA MORE", label: "CHITTA MORE" },
  { value: "CHOA KHALSA", label: "CHOA KHALSA" },
  { value: "CHOA SAIDAN SHAH", label: "CHOA SAIDAN SHAH" },
  { value: "CHOBARA", label: "CHOBARA" },
  { value: "CHOR", label: "CHOR" },
  { value: "CHOTA LAHORE", label: "CHOTA LAHORE" },
  { value: "CHOTA SAHIWAL", label: "CHOTA SAHIWAL" },
  { value: "CHOWK AZAM", label: "CHOWK AZAM" },
  { value: "CHOWK MUNDA", label: "CHOWK MUNDA" },
  { value: "CHOWK PANDORI", label: "CHOWK PANDORI" },
  { value: "CHUHAR JAMALI", label: "CHUHAR JAMALI" },
  { value: "CHUKYATAN", label: "CHUKYATAN" },
  { value: "CHUNAWALA", label: "CHUNAWALA" },
  { value: "CHUNIAN", label: "CHUNIAN" },
  { value: "DADU", label: "DADU" },
  { value: "DADYAL (AJK)", label: "DADYAL (AJK)" },
  { value: "DAGGAR", label: "DAGGAR" },
  { value: "DAGHONI BALGAR", label: "DAGHONI BALGAR" },
  { value: "DAKWALA", label: "DAKWALA" },
  { value: "DAMBODAS", label: "DAMBODAS" },
  { value: "DANDA SHAH BILAWAL", label: "DANDA SHAH BILAWAL" },
  { value: "DAOOD ZAI", label: "DAOOD ZAI" },
  { value: "DARGAI", label: "DARGAI" },
  { value: "DARMAN", label: "DARMAN" },
  { value: "DARORA", label: "DARORA" },
  { value: "DARRO", label: "DARRO" },
  { value: "DARYA GALI", label: "DARYA GALI" },
  { value: "DARYA KHAN", label: "DARYA KHAN" },
  { value: "DASKA", label: "DASKA" },
  { value: "DAUD KHEL", label: "DAUD KHEL" },
  { value: "DAUL TALA", label: "DAUL TALA" },
  { value: "DAULATPUR", label: "DAULATPUR" },
  { value: "DAUR", label: "DAUR" },
  { value: "DEHARKI", label: "DEHARKI" },
  { value: "DEHLA CHATTHA", label: "DEHLA CHATTHA" },
  { value: "DEPALPUR", label: "DEPALPUR" },
  { value: "DERA ALLAH YAR", label: "DERA ALLAH YAR" },
  { value: "DERA GHAZI KHAN", label: "DERA GHAZI KHAN" },
  { value: "DERA ISMAIL KHAN", label: "DERA ISMAIL KHAN" },
  { value: "DERA MURAD JAMALI", label: "DERA MURAD JAMALI" },
  { value: "DERA NAWAB", label: "DERA NAWAB" },
  { value: "DEWAL", label: "DEWAL" },
  { value: "DEWALAY", label: "DEWALAY" },
  { value: "DEWANA BABA", label: "DEWANA BABA" },
  { value: "DHABJEE", label: "DHABJEE" },
  { value: "DHAKKAR", label: "DHAKKAR" },
  { value: "DHARABI", label: "DHARABI" },
  { value: "DHARYALA JALAP", label: "DHARYALA JALAP" },
  { value: "DHERI ARAIAN", label: "DHERI ARAIAN" },
  { value: "DHIRKOT", label: "DHIRKOT" },
  { value: "DHOKE SHAHANI", label: "DHOKE SHAHANI" },
  { value: "DHORI ADDA", label: "DHORI ADDA" },
  { value: "DHUDIAL", label: "DHUDIAL" },
  { value: "DHULIAN", label: "DHULIAN" },
  { value: "DHURNAL", label: "DHURNAL" },
  { value: "DIGRI", label: "DIGRI" },
  { value: "DIJKOT", label: "DIJKOT" },
  { value: "DILAWAR CHEEMA", label: "DILAWAR CHEEMA" },
  { value: "DINA", label: "DINA" },
  { value: "Dina Nath", label: "Dina Nath" },
  { value: "DINGA", label: "DINGA" },
  { value: "DISTT. COMPLEX", label: "DISTT. COMPLEX" },
  { value: "DOABA", label: "DOABA" },
  { value: "DOBERAN KALLAN", label: "DOBERAN KALLAN" },
  { value: "DOKRI", label: "DOKRI" },
  { value: "DONGA BONGA", label: "DONGA BONGA" },
  { value: "Doughal", label: "Doughal" },
  { value: "DROSH", label: "DROSH" },
  { value: "DUDHU CHAK", label: "DUDHU CHAK" },
  { value: "DULLE WALA", label: "DULLE WALA" },
  { value: "DUNIAPUR", label: "DUNIAPUR" },
  { value: "DUNYA PUR", label: "DUNYA PUR" },
  { value: "F.F.C. PLANT", label: "F.F.C. PLANT" },
  { value: "Faisalabad", label: "Faisalabad" },
  { value: "FAQIRWALI", label: "FAQIRWALI" },
  { value: "FARHAT ABAD", label: "FARHAT ABAD" },
  { value: "FAROKA", label: "FAROKA" },
  { value: "FAROOQABAD", label: "FAROOQABAD" },
  { value: "FATEH JANG", label: "FATEH JANG" },
  { value: "FATEH PUR", label: "FATEH PUR" },
  { value: "FATEH PUR KAMAL", label: "FATEH PUR KAMAL" },
  { value: "FATEHPUR", label: "FATEHPUR" },
  { value: "FATEHPUR THAKIALA", label: "FATEHPUR THAKIALA" },
  { value: "FATTA BHAND", label: "FATTA BHAND" },
  { value: "FAZIL PUR", label: "FAZIL PUR" },
  { value: "FEROZ WATWAN", label: "FEROZ WATWAN" },
  { value: "FEROZEWALA", label: "FEROZEWALA" },
  { value: "FKPCL POWER PLANT", label: "FKPCL POWER PLANT" },
  { value: "FORT ABBAS", label: "FORT ABBAS" },
  { value: "FORWARD KAHUTA", label: "FORWARD KAHUTA" },
  { value: "GAGAN", label: "GAGAN" },
  { value: "GAGGO MANDI", label: "GAGGO MANDI" },
  { value: "GALI JAGIR", label: "GALI JAGIR" },
  { value: "GAMBA SKARDU", label: "GAMBA SKARDU" },
  { value: "GAMBAT", label: "GAMBAT" },
  { value: "GAMBER", label: "GAMBER" },
  { value: "GANORI", label: "GANORI" },
  { value: "GARH MAHARAJA", label: "GARH MAHARAJA" },
  { value: "GARH MORE", label: "GARH MORE" },
  { value: "GARHA MORE", label: "GARHA MORE" },
  { value: "GARHI DUPATTA", label: "GARHI DUPATTA" },
  { value: "GARHI MORI", label: "GARHI MORI" },
  { value: "GATWALA 199 / RB", label: "GATWALA 199 / RB" },
  { value: "GHAKKAR MANDI", label: "GHAKKAR MANDI" },
  { value: "GHALANY", label: "GHALANY" },
  { value: "GHAR MORE", label: "GHAR MORE" },
  { value: "GHARI HABIBULLAH", label: "GHARI HABIBULLAH" },
  { value: "GHARIAL CAMP", label: "GHARIAL CAMP" },
  { value: "GHARIBWAL", label: "GHARIBWAL" },
  { value: "GHARIBWAL CEMENT", label: "GHARIBWAL CEMENT" },
  { value: "GHARO", label: "GHARO" },
  { value: "GHAZI", label: "GHAZI" },
  { value: "GHAZIABAD", label: "GHAZIABAD" },
  { value: "GHIKA GALI", label: "GHIKA GALI" },
  { value: "GHORA GALI", label: "GHORA GALI" },
  { value: "GHOTKI", label: "GHOTKI" },
  { value: "GHOUR GHUSTI", label: "GHOUR GHUSTI" },
  { value: "GHOUS PUR", label: "GHOUS PUR" },
  { value: "GHOUSPUR", label: "GHOUSPUR" },
  { value: "GHUMMAN WALA", label: "GHUMMAN WALA" },
  { value: "GILGIT", label: "GILGIT" },
  { value: "GOJRA", label: "GOJRA" },
  { value: "GOLARCHI", label: "GOLARCHI" },
  { value: "GOLPUR", label: "GOLPUR" },
  { value: "GOTH MACHI", label: "GOTH MACHI" },
  { value: "GUJAR KHAN", label: "GUJAR KHAN" },
  { value: "GUJRANWALA", label: "GUJRANWALA" },
  { value: "GUJRAT", label: "GUJRAT" },
  { value: "GUL BELA", label: "GUL BELA" },
  { value: "GULYANA", label: "GULYANA" },
  { value: "GUMTI SHAREEF", label: "GUMTI SHAREEF" },
  { value: "GUNJA", label: "GUNJA" },
  { value: "GURMANI ADDA", label: "GURMANI ADDA" },
  { value: "GWADAR", label: "GWADAR" },
  { value: "Habib Abad", label: "Habib Abad" },
  { value: "Hafiz Hayat Campus", label: "Hafiz Hayat Campus" },
  { value: "HAFIZABAD", label: "HAFIZABAD" },
  { value: "HAJEERA", label: "HAJEERA" },
  { value: "HAJIRA", label: "HAJIRA" },
  { value: "HAKIM ABAD", label: "HAKIM ABAD" },
  { value: "HALA", label: "HALA" },
  { value: "Halla", label: "Halla" },
  { value: "HANGU", label: "HANGU" },
  { value: "HARANPUR", label: "HARANPUR" },
  { value: "HARAPPA", label: "HARAPPA" },
  { value: "HARIGHEL", label: "HARIGHEL" },
  { value: "HARIPUR", label: "HARIPUR" },
  { value: "HARNAL", label: "HARNAL" },
  { value: "HAROONABAD", label: "HAROONABAD" },
  { value: "HASEEB WAQAS MILLS", label: "HASEEB WAQAS MILLS" },
  { value: "HASIL PUR", label: "HASIL PUR" },
  { value: "HASLANWALA", label: "HASLANWALA" },
  { value: "HASSAN ABDAL", label: "HASSAN ABDAL" },
  { value: "HATIA BALA", label: "HATIA BALA" },
  { value: "HATTAR", label: "HATTAR" },
  { value: "HATTIAN BALA", label: "HATTIAN BALA" },
  { value: "HAVELI BAHADUR SHAH", label: "HAVELI BAHADUR SHAH" },
  { value: "HAVELI LAKHA", label: "HAVELI LAKHA" },
  { value: "HAVELIAN", label: "HAVELIAN" },
  { value: "HAZARA UNIVERSITY", label: "HAZARA UNIVERSITY" },
  { value: "HAZRAT KALIANWALA", label: "HAZRAT KALIANWALA" },
  { value: "HAZRO", label: "HAZRO" },
  { value: "HEAD BALOKI ROAD", label: "HEAD BALOKI ROAD" },
  { value: "HEAD KHOKHRA", label: "HEAD KHOKHRA" },
  { value: "HEADMARALA", label: "HEADMARALA" },
  { value: "HUB", label: "HUB" },
  { value: "HUB CHOWKI", label: "HUB CHOWKI" },
  { value: "HUJRA SHAH MUKEEM", label: "HUJRA SHAH MUKEEM" },
  { value: "HUNZA–NAGAR", label: "HUNZA–NAGAR" },
  { value: "HUSRI", label: "HUSRI" },
  { value: "HUSSAINABAD", label: "HUSSAINABAD" },
  { value: "HYDERABAD", label: "HYDERABAD" },
  { value: "IIKHLAS", label: "IIKHLAS" },
  { value: "IKHLASPUR", label: "IKHLASPUR" },
  { value: "IQBAL ABAD", label: "IQBAL ABAD" },
  { value: "IQBAL NAGAR", label: "IQBAL NAGAR" },
  { value: "ISLAM GARH (AJK)", label: "ISLAM GARH (AJK)" },
  { value: "ISLAM HEADWORKS", label: "ISLAM HEADWORKS" },
  { value: "Islamabad", label: "Islamabad" },
  { value: "ISLAMGARH", label: "ISLAMGARH" },
  { value: "JABBI SHAH DILAWAR", label: "JABBI SHAH DILAWAR" },
  { value: "JACOBABAD", label: "JACOBABAD" },
  { value: "JAFARABAD", label: "JAFARABAD" },
  { value: "JAFFAR MANDI", label: "JAFFAR MANDI" },
  { value: "JAHANIAN", label: "JAHANIAN" },
  { value: "JALALPUR BHATTIAN", label: "JALALPUR BHATTIAN" },
  { value: "JALALPUR JATTAN", label: "JALALPUR JATTAN" },
  { value: "JALALPUR SHARIF", label: "JALALPUR SHARIF" },
  { value: "JALALPURPIRWALA", label: "JALALPURPIRWALA" },
  { value: "JAMALPUR", label: "JAMALPUR" },
  { value: "JAMKE CHATHA", label: "JAMKE CHATHA" },
  { value: "JAMPUR", label: "JAMPUR" },
  { value: "JAMSHORO", label: "JAMSHORO" },
  { value: "JANDIA SHER KHAN", label: "JANDIA SHER KHAN" },
  { value: "JANI CHAK", label: "JANI CHAK" },
  { value: "Janu Chak", label: "Janu Chak" },
  { value: "JARANWALA", label: "JARANWALA" },
  { value: "JASIAL", label: "JASIAL" },
  { value: "JATLAN (AJK)", label: "JATLAN (AJK)" },
  { value: "JATOI", label: "JATOI" },
  { value: "JAURAH", label: "JAURAH" },
  { value: "JEHANGIRA", label: "JEHANGIRA" },
  { value: "JHABRAN MANDI", label: "JHABRAN MANDI" },
  { value: "JHANG", label: "JHANG" },
  { value: "JHELUM", label: "JHELUM" },
  { value: "JHOL", label: "JHOL" },
  { value: "JHUDDO", label: "JHUDDO" },
  { value: "JOHARABAD", label: "JOHARABAD" },
  { value: "JOHI", label: "JOHI" },
  { value: "JUGLOT", label: "JUGLOT" },
  { value: "JUTANA", label: "JUTANA" },
  { value: "KABAL", label: "KABAL" },
  { value: "KABIRWALA", label: "KABIRWALA" },
  { value: "KACHA KHOO", label: "KACHA KHOO" },
  { value: "KACHURA", label: "KACHURA" },
  { value: "KADHAN", label: "KADHAN" },
  { value: "KAHAUTA", label: "KAHAUTA" },
  { value: "KAHUTA", label: "KAHUTA" },
  { value: "KAIRPUR NATHIN SHAH", label: "KAIRPUR NATHIN SHAH" },
  { value: "KALASKE CHEEMA", label: "KALASKE CHEEMA" },
  { value: "KALASWALA", label: "KALASWALA" },
  { value: "KALI MITTI", label: "KALI MITTI" },
  { value: "KALKOT", label: "KALKOT" },
  { value: "KALLAR KAHAR", label: "KALLAR KAHAR" },
  { value: "KALLAR SYEDDAN", label: "KALLAR SYEDDAN" },
  { value: "KALOR KOT", label: "KALOR KOT" },
  { value: "KAMALIA", label: "KAMALIA" },
  { value: "KAMOKE", label: "KAMOKE" },
  { value: "KAMRA", label: "KAMRA" },
  { value: "KAMRIAL", label: "KAMRIAL" },
  { value: "KAND KOT", label: "KAND KOT" },
  { value: "KANDHKOT", label: "KANDHKOT" },
  { value: "KANDIARO", label: "KANDIARO" },
  { value: "KANGAN PUR", label: "KANGAN PUR" },
  { value: "KANGRA", label: "KANGRA" },
  { value: "KANJU", label: "KANJU" },
  { value: "KANOHA", label: "KANOHA" },
  { value: "KANYAL", label: "KANYAL" },
  { value: "KAPCO POWER PLANT", label: "KAPCO POWER PLANT" },
  { value: "Karachi", label: "Karachi" },
  { value: "KARACHI ALHYDRI", label: "KARACHI ALHYDRI" },
  { value: "KARACHI CITY", label: "KARACHI CITY" },
  { value: "KARACHI SADDAR", label: "KARACHI SADDAR" },
  { value: "KARAK", label: "KARAK" },
  { value: "KARAM PUR", label: "KARAM PUR" },
  { value: "KARARIWALA KHURD", label: "KARARIWALA KHURD" },
  { value: "KARIALA JALIB", label: "KARIALA JALIB" },
  { value: "KAROOR PAKA", label: "KAROOR PAKA" },
  { value: "KAROR LAL EASAN", label: "KAROR LAL EASAN" },
  { value: "KARTARPUR", label: "KARTARPUR" },
  { value: "KASHMIR POINT", label: "KASHMIR POINT" },
  { value: "KASHMORE", label: "KASHMORE" },
  { value: "KASSOWAL", label: "KASSOWAL" },
  { value: "KASUR", label: "KASUR" },
  { value: "KATHORE", label: "KATHORE" },
  { value: "KERIS", label: "KERIS" },
  { value: "KHAI GALA", label: "KHAI GALA" },
  { value: "KHAIRPUR", label: "KHAIRPUR" },
  { value: "KHAIRPUR MEERUS", label: "KHAIRPUR MEERUS" },
  { value: "KHAIRPUR NATHAN SHAH", label: "KHAIRPUR NATHAN SHAH" },
  { value: "KHAIRPUR TAMEWALI", label: "KHAIRPUR TAMEWALI" },
  { value: "KHAN BELA", label: "KHAN BELA" },
  { value: "KHAN GHAR", label: "KHAN GHAR" },
  { value: "KHANEWAL", label: "KHANEWAL" },
  { value: "KHANKA DOGRAN", label: "KHANKA DOGRAN" },
  { value: "KHANPUR", label: "KHANPUR" },
  { value: "KHANPUR MAHAR", label: "KHANPUR MAHAR" },
  { value: "KHAPLU", label: "KHAPLU" },
  { value: "KHARALA", label: "KHARALA" },
  { value: "KHARIAN", label: "KHARIAN" },
  { value: "KHARMANG", label: "KHARMANG" },
  { value: "KHAS BEHAAL", label: "KHAS BEHAAL" },
  { value: "KHAUR", label: "KHAUR" },
  { value: "KHIDARWALA", label: "KHIDARWALA" },
  { value: "KHIPRO", label: "KHIPRO" },
  { value: "KHOAZA KHAILA", label: "KHOAZA KHAILA" },
  { value: "KHOHAR", label: "KHOHAR" },
  { value: "KHORI ALAM", label: "KHORI ALAM" },
  { value: "KHOSKI", label: "KHOSKI" },
  { value: "KHUDIAN KHAS", label: "KHUDIAN KHAS" },
  { value: "KHUHRA", label: "KHUHRA" },
  { value: "KHUIRATTA", label: "KHUIRATTA" },
  { value: "KHUNDA", label: "KHUNDA" },
  { value: "KHURRIANWALA", label: "KHURRIANWALA" },
  { value: "KHUSHAB", label: "KHUSHAB" },
  { value: "KHUZDAR", label: "KHUZDAR" },
  { value: "KHWAGO OBO", label: "KHWAGO OBO" },
  { value: "KHWAZAKHELA", label: "KHWAZAKHELA" },
  { value: "KHWERA", label: "KHWERA" },
  { value: "KINGRA MOR", label: "KINGRA MOR" },
  { value: "KML via CCW", label: "KML via CCW" },
  { value: "KOHAT", label: "KOHAT" },
  { value: "KORANGI KARACHI", label: "KORANGI KARACHI" },
  { value: "KOT ABDUL MALIK", label: "KOT ABDUL MALIK" },
  { value: "KOT ADDU", label: "KOT ADDU" },
  { value: "KOT ASLAM", label: "KOT ASLAM" },
  { value: "KOT BANGLO", label: "KOT BANGLO" },
  { value: "KOT BARAY KHAN", label: "KOT BARAY KHAN" },
  { value: "KOT BILAL", label: "KOT BILAL" },
  { value: "KOT CHUTTA", label: "KOT CHUTTA" },
  { value: "KOT FATEH KHAN", label: "KOT FATEH KHAN" },
  { value: "KOT GHULAM MUHAMMAD", label: "KOT GHULAM MUHAMMAD" },
  { value: "KOT MITHAN", label: "KOT MITHAN" },
  { value: "KOT MOMIN", label: "KOT MOMIN" },
  { value: "KOT NAINAN", label: "KOT NAINAN" },
  { value: "KOT PINDI DAS", label: "KOT PINDI DAS" },
  { value: "KOT QADIR BAKHSH", label: "KOT QADIR BAKHSH" },
  { value: "KOT QAISRANI", label: "KOT QAISRANI" },
  { value: "KOT QAZI", label: "KOT QAZI" },
  { value: "KOT RADHA KISHAN", label: "KOT RADHA KISHAN" },
  { value: "KOT SAMABAH", label: "KOT SAMABAH" },
  { value: "KOTANAI", label: "KOTANAI" },
  { value: "KOTKAY", label: "KOTKAY" },
  { value: "KOTLA ARAB ALI KHAN", label: "KOTLA ARAB ALI KHAN" },
  { value: "KOTLI BEHRAM", label: "KOTLI BEHRAM" },
  { value: "KOTLI LOHARAN", label: "KOTLI LOHARAN" },
  { value: "KOTRI", label: "KOTRI" },
  { value: "KOTRI MUHAMMAD KABIR", label: "KOTRI MUHAMMAD KABIR" },
  { value: "KUCHLAK", label: "KUCHLAK" },
  { value: "KULACHI", label: "KULACHI" },
  { value: "KULDANA", label: "KULDANA" },
  { value: "KULLUWAL", label: "KULLUWAL" },
  { value: "KUMB", label: "KUMB" },
  { value: "KUNDIAN", label: "KUNDIAN" },
  { value: "KUNJAH", label: "KUNJAH" },
  { value: "KUNRI", label: "KUNRI" },
  { value: "Kuthyala Syedan", label: "Kuthyala Syedan" },
  { value: "Ladha Sadha", label: "Ladha Sadha" },
  { value: "LADHEWALA CHEEMA", label: "LADHEWALA CHEEMA" },
  { value: "Lahore", label: "Lahore" },
  { value: "LAHORE CANTT", label: "LAHORE CANTT" },
  { value: "LAIDHER", label: "LAIDHER" },
  { value: "Lake City", label: "Lake City" },
  { value: "LAKHA ROAD", label: "LAKHA ROAD" },
  { value: "LAKHNE WALA", label: "LAKHNE WALA" },
  { value: "LAKKI MARWAT", label: "LAKKI MARWAT" },
  { value: "LALA CHAK", label: "LALA CHAK" },
  { value: "LALA MUSA", label: "LALA MUSA" },
  { value: "LALIAN", label: "LALIAN" },
  { value: "LALLIAN", label: "LALLIAN" },
  { value: "LALLIANI", label: "LALLIANI" },
  { value: "LALPIR (THERMAL POWER)", label: "LALPIR (THERMAL POWER)" },
  { value: "LARKANA", label: "LARKANA" },
  { value: "LASOORI KALAN", label: "LASOORI KALAN" },
  { value: "LAWA", label: "LAWA" },
  { value: "LAWRENCE PUR", label: "LAWRENCE PUR" },
  { value: "LAYYAH", label: "LAYYAH" },
  { value: "LESSAR KALAN", label: "LESSAR KALAN" },
  { value: "LIAQAT NATIONAL BAGH AKA COMPANY BAGH", label: "LIAQAT NATIONAL BAGH AKA COMPANY BAGH" },
  { value: "LIAQAT PUR", label: "LIAQAT PUR" },
  { value: "LIAQUATABAD", label: "LIAQUATABAD" },
  { value: "LILLA", label: "LILLA" },
  { value: "LODHRAN", label: "LODHRAN" },
  { value: "LORALAI", label: "LORALAI" },
  { value: "LOWARI", label: "LOWARI" },
  { value: "LOWER BAZAR", label: "LOWER BAZAR" },
  { value: "LOWER CHITRAL", label: "LOWER CHITRAL" },
  { value: "LOWER DIR", label: "LOWER DIR" },
  { value: "LOWER TOPA", label: "LOWER TOPA" },
  { value: "MACHIKEY", label: "MACHIKEY" },
  { value: "MACHIWAL", label: "MACHIWAL" },
  { value: "MADRASSA CHATTHA", label: "MADRASSA CHATTHA" },
  { value: "MADYAN", label: "MADYAN" },
  { value: "MAILSI", label: "MAILSI" },
  { value: "MAIRA SHARIF", label: "MAIRA SHARIF" },
  { value: "MAJJU CHAK", label: "MAJJU CHAK" },
  { value: "MAKLI", label: "MAKLI" },
  { value: "MALAKAND", label: "MALAKAND" },
  { value: "MALAKWAL", label: "MALAKWAL" },
  { value: "MAMDOT", label: "MAMDOT" },
  { value: "MAMU KANJAN", label: "MAMU KANJAN" },
  { value: "MANA WLA", label: "MANA WLA" },
  { value: "MANAWALA", label: "MANAWALA" },
  { value: "MANCHAR CHATTHA", label: "MANCHAR CHATTHA" },
  { value: "MANDI BAHAUDDIN", label: "MANDI BAHAUDDIN" },
  { value: "MANDI BUCHIANA", label: "MANDI BUCHIANA" },
  { value: "MANDI SAFDAR ABAD", label: "MANDI SAFDAR ABAD" },
  { value: "MANDI USMAN WALA", label: "MANDI USMAN WALA" },
  { value: "MANDIAN", label: "MANDIAN" },
  { value: "MANDRA", label: "MANDRA" },
  { value: "MANGA MANDI", label: "MANGA MANDI" },
  { value: "Mangat", label: "Mangat" },
  { value: "MANGLA (AJK)", label: "MANGLA (AJK)" },
  { value: "MANGLA CANTT (AJK)", label: "MANGLA CANTT (AJK)" },
  { value: "MANKERA", label: "MANKERA" },
  { value: "MANKYLA STATION", label: "MANKYLA STATION" },
  { value: "MANSEHRA", label: "MANSEHRA" },
  { value: "MANTHAL", label: "MANTHAL" },
  { value: "MARDAN", label: "MARDAN" },
  { value: "MARI", label: "MARI" },
  { value: "MASAR CAMP", label: "MASAR CAMP" },
  { value: "MATIARI", label: "MATIARI" },
  { value: "MATLI", label: "MATLI" },
  { value: "MATORE", label: "MATORE" },
  { value: "MATTA", label: "MATTA" },
  { value: "MEHAR", label: "MEHAR" },
  { value: "MEHDIABAD", label: "MEHDIABAD" },
  { value: "MEHER", label: "MEHER" },
  { value: "MEHMOOD KOT", label: "MEHMOOD KOT" },
  { value: "MEHRAB PUR", label: "MEHRAB PUR" },
  { value: "MIAN CHANNU", label: "MIAN CHANNU" },
  { value: "MIAN WALI QURESHAIN", label: "MIAN WALI QURESHAIN" },
  { value: "MIANA GONDAL", label: "MIANA GONDAL" },
  { value: "MIANDAM", label: "MIANDAM" },
  { value: "MIANI", label: "MIANI" },
  { value: "MIANWALI", label: "MIANWALI" },
  { value: "MIANWALI BANGLA", label: "MIANWALI BANGLA" },
  { value: "MINCHINABAD", label: "MINCHINABAD" },
  { value: "MINGORA", label: "MINGORA" },
  { value: "MIR PUR METHELO", label: "MIR PUR METHELO" },
  { value: "MIRAK SIAL", label: "MIRAK SIAL" },
  { value: "MIRPUR (AJK)", label: "MIRPUR (AJK)" },
  { value: "MIRPUR BATHORO", label: "MIRPUR BATHORO" },
  { value: "MIRPUR KHAS", label: "MIRPUR KHAS" },
  { value: "MIRPUR MATHELO", label: "MIRPUR MATHELO" },
  { value: "MIRPUR SAKRO", label: "MIRPUR SAKRO" },
  { value: "MITHA TIWANA", label: "MITHA TIWANA" },
  { value: "MITHI", label: "MITHI" },
  { value: "MITTHI", label: "MITTHI" },
  { value: "MOHALLA RAJGAN", label: "MOHALLA RAJGAN" },
  { value: "MOR AIMANABAD", label: "MOR AIMANABAD" },
  { value: "MORE AIMANABAD", label: "MORE AIMANABAD" },
  { value: "MORE KHUNDA", label: "MORE KHUNDA" },
  { value: "MORO", label: "MORO" },
  { value: "MOTRA", label: "MOTRA" },
  { value: "MUHAMMAD PANAH MOR", label: "MUHAMMAD PANAH MOR" },
  { value: "MULTAN", label: "MULTAN" },
  { value: "MULTAN KHURD", label: "MULTAN KHURD" },
  { value: "MUNDA", label: "MUNDA" },
  { value: "MUNDI KHEL", label: "MUNDI KHEL" },
  { value: "MURALI", label: "MURALI" },
  { value: "MURALI WALA", label: "MURALI WALA" },
  { value: "MURAT", label: "MURAT" },
  { value: "MURIDKE", label: "MURIDKE" },
  { value: "MURREE", label: "MURREE" },
  { value: "MUZAFFARABAD (AJK)", label: "MUZAFFARABAD (AJK)" },
  { value: "MUZAFFARGARH", label: "MUZAFFARGARH" },
  { value: "NAKKA KAHUT", label: "NAKKA KAHUT" },
  { value: "NANKANA SAHIB", label: "NANKANA SAHIB" },
  { value: "NARA", label: "NARA" },
  { value: "NARANG MANDI", label: "NARANG MANDI" },
  { value: "NARAR", label: "NARAR" },
  { value: "NAROWAL", label: "NAROWAL" },
  { value: "NASARPUR", label: "NASARPUR" },
  { value: "NASIRABAD", label: "NASIRABAD" },
  { value: "NATHIA GALI", label: "NATHIA GALI" },
  { value: "NAUSHAHRO FEROZE", label: "NAUSHAHRO FEROZE" },
  { value: "NAWABSHAH", label: "NAWABSHAH" },
  { value: "NAWAN SHEHR", label: "NAWAN SHEHR" },
  { value: "NAWAY KALI", label: "NAWAY KALI" },
  { value: "NAYA LAHORE", label: "NAYA LAHORE" },
  { value: "NEW INDUSTRIAL AREA", label: "NEW INDUSTRIAL AREA" },
  { value: "NEW MURREE", label: "NEW MURREE" },
  { value: "NEW TOWN KARACHI", label: "NEW TOWN KARACHI" },
  { value: "NIZAMABAD", label: "NIZAMABAD" },
  { value: "NOKHAR", label: "NOKHAR" },
  { value: "NOMAN PORA", label: "NOMAN PORA" },
  { value: "NONAR", label: "NONAR" },
  { value: "NOOR COLONY", label: "NOOR COLONY" },
  { value: "NOOR JAMAAL", label: "NOOR JAMAAL" },
  { value: "NOOR KOT", label: "NOOR KOT" },
  { value: "NOORPUR", label: "NOORPUR" },
  { value: "NOORPUR THAL", label: "NOORPUR THAL" },
  { value: "NORIABAD", label: "NORIABAD" },
  { value: "NOWSHERA", label: "NOWSHERA" },
  { value: "NOWSHERA KALAN", label: "NOWSHERA KALAN" },
  { value: "NOWSHERA VIRKAN", label: "NOWSHERA VIRKAN" },
  { value: "NRTC (TELECOM STAFF COLLEGE)", label: "NRTC (TELECOM STAFF COLLEGE)" },
  { value: "NUDEARO", label: "NUDEARO" },
  { value: "OKARA", label: "OKARA" },
  { value: "OLD HALA", label: "OLD HALA" },
  { value: "OLDING", label: "OLDING" },
  { value: "P.O.F. (FACTORY & COLONY)", label: "P.O.F. (FACTORY & COLONY)" },
  { value: "PABBI", label: "PABBI" },
  { value: "PABI", label: "PABI" },
  { value: "PACHNAND", label: "PACHNAND" },
  { value: "PAHARPUR", label: "PAHARPUR" },
  { value: "PAK PATTAN SHARIF", label: "PAK PATTAN SHARIF" },
  { value: "PAKKA LARAN", label: "PAKKA LARAN" },
  { value: "PAKPATTAN", label: "PAKPATTAN" },
  { value: "PALANDRI", label: "PALANDRI" },
  { value: "PANAKOT", label: "PANAKOT" },
  { value: "PANJAN SHER SHAHANA", label: "PANJAN SHER SHAHANA" },
  { value: "PANO AKIL", label: "PANO AKIL" },
  { value: "PANOAQIL", label: "PANOAQIL" },
  { value: "PAROA", label: "PAROA" },
  { value: "PASNI", label: "PASNI" },
  { value: "PASROOR", label: "PASROOR" },
  { value: "PASROOR ROAD AND VILLAGES", label: "PASROOR ROAD AND VILLAGES" },
  { value: "PASRUR", label: "PASRUR" },
  { value: "PATHIKA", label: "PATHIKA" },
  { value: "PATOKI", label: "PATOKI" },
  { value: "PATRAK", label: "PATRAK" },
  { value: "PATRIATA", label: "PATRIATA" },
  { value: "PATTOKI", label: "PATTOKI" },
  { value: "PEER KALAN", label: "PEER KALAN" },
  { value: "PEER MAHAL", label: "PEER MAHAL" },
  { value: "PESHAWAR", label: "PESHAWAR" },
  { value: "PEZU", label: "PEZU" },
  { value: "PHAGWARI", label: "PHAGWARI" },
  { value: "PHALIA", label: "PHALIA" },
  { value: "PHOOL NAGAR", label: "PHOOL NAGAR" },
  { value: "PINANWAL", label: "PINANWAL" },
  { value: "PIND DADAN KHAN", label: "PIND DADAN KHAN" },
  { value: "PINDI BHATIAN", label: "PINDI BHATIAN" },
  { value: "PINDI GHEB", label: "PINDI GHEB" },
  { value: "PINDI GUJRAN", label: "PINDI GUJRAN" },
  { value: "PINDI POINT", label: "PINDI POINT" },
  { value: "PINDI SAID PUR", label: "PINDI SAID PUR" },
  { value: "PIPLAN", label: "PIPLAN" },
  { value: "PIR BABA", label: "PIR BABA" },
  { value: "PIR JO GOTH", label: "PIR JO GOTH" },
  { value: "PIR WASAN", label: "PIR WASAN" },
  { value: "PIRA FATEHAL", label: "PIRA FATEHAL" },
  { value: "PIRJOGOTH", label: "PIRJOGOTH" },
  { value: "PIRYALOI", label: "PIRYALOI" },
  { value: "PISHIN", label: "PISHIN" },
  { value: "PITARO", label: "PITARO" },
  { value: "PMA KAKUL", label: "PMA KAKUL" },
  { value: "POONCH (AJK)", label: "POONCH (AJK)" },
  { value: "PORANWALA", label: "PORANWALA" },
  { value: "PUNGIRAYIN", label: "PUNGIRAYIN" },
  { value: "PUNJAR", label: "PUNJAR" },
  { value: "PUNWAN", label: "PUNWAN" },
  { value: "PURAAN", label: "PURAAN" },
  { value: "QABAL", label: "QABAL" },
  { value: "QABOOLA SHARIF", label: "QABOOLA SHARIF" },
  { value: "QADIR PUR RAWAN", label: "QADIR PUR RAWAN" },
  { value: "QAIDABAD", label: "QAIDABAD" },
  { value: "QAIM BHARWANA", label: "QAIM BHARWANA" },
  { value: "QAIMPUR", label: "QAIMPUR" },
  { value: "QALAT", label: "QALAT" },
  { value: "QAMAR ABAD", label: "QAMAR ABAD" },
  { value: "QAMAR MASHANI", label: "QAMAR MASHANI" },
  { value: "QAMBAR", label: "QAMBAR" },
  { value: "QASBA GUJRAT.", label: "QASBA GUJRAT." },
  { value: "QASHQARY", label: "QASHQARY" },
  { value: "QASIMPURA", label: "QASIMPURA" },
  { value: "QAZI AHMED", label: "QAZI AHMED" },
  { value: "QILA AHMED ABAD", label: "QILA AHMED ABAD" },
  { value: "QILA DEEDAR SING", label: "QILA DEEDAR SING" },
  { value: "QILA KALAR WALA", label: "QILA KALAR WALA" },
  { value: "QILA SAIB SINGH", label: "QILA SAIB SINGH" },
  { value: "QUETTA", label: "QUETTA" },
  { value: "QULANDI", label: "QULANDI" },
  { value: "RABAT", label: "RABAT" },
  { value: "RACHNA TOWN", label: "RACHNA TOWN" },
  { value: "RADHAN", label: "RADHAN" },
  { value: "RAHIM YAR KHAN", label: "RAHIM YAR KHAN" },
  { value: "RAHIMYAR KHAN", label: "RAHIMYAR KHAN" },
  { value: "RAIWIND", label: "RAIWIND" },
  { value: "RAJA JANG", label: "RAJA JANG" },
  { value: "RAJANA", label: "RAJANA" },
  { value: "RAJANPUR", label: "RAJANPUR" },
  { value: "RAJAR", label: "RAJAR" },
  { value: "RAKH BALOCH KALAN", label: "RAKH BALOCH KALAN" },
  { value: "RAMAK", label: "RAMAK" },
  { value: "RANI PUR", label: "RANI PUR" },
  { value: "RAO KHAN WALA", label: "RAO KHAN WALA" },
  { value: "RASHAKI", label: "RASHAKI" },
  { value: "RASOOL NAGAR", label: "RASOOL NAGAR" },
  { value: "RATO DEARO", label: "RATO DEARO" },
  { value: "RATODERO", label: "RATODERO" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "RAWAT", label: "RAWAT" },
  { value: "REHANKOT", label: "REHANKOT" },
  { value: "RENALA KHURD", label: "RENALA KHURD" },
  { value: "RISALPUR", label: "RISALPUR" },
  { value: "ROHRI", label: "ROHRI" },
  { value: "ROUNDU", label: "ROUNDU" },
  { value: "RUBWA", label: "RUBWA" },
  { value: "Rukkan", label: "Rukkan" },
  { value: "SABAZ PEER", label: "SABAZ PEER" },
  { value: "SADAT PUR", label: "SADAT PUR" },
  { value: "SADIQABAD", label: "SADIQABAD" },
  { value: "SADPARA", label: "SADPARA" },
  { value: "SAFDARABAD", label: "SAFDARABAD" },
  { value: "SAGHAR PUR", label: "SAGHAR PUR" },
  { value: "SAHARAN CHATTHA", label: "SAHARAN CHATTHA" },
  { value: "SAHIWAL", label: "SAHIWAL" },
  { value: "SAID NAGAR", label: "SAID NAGAR" },
  { value: "Said Pur Gondal", label: "Said Pur Gondal" },
  { value: "SAIDU SHAIRF", label: "SAIDU SHAIRF" },
  { value: "SAIDU SHARIF", label: "SAIDU SHARIF" },
  { value: "SAJAWAL", label: "SAJAWAL" },
  { value: "SAKHAKOT", label: "SAKHAKOT" },
  { value: "SAKRAND", label: "SAKRAND" },
  { value: "SALLHOKE CHATTHA", label: "SALLHOKE CHATTHA" },
  { value: "SAMANDARI", label: "SAMANDARI" },
  { value: "SAMAR BAGH", label: "SAMAR BAGH" },
  { value: "SAMARO", label: "SAMARO" },
  { value: "SAMBRIAL", label: "SAMBRIAL" },
  { value: "SAMOTE", label: "SAMOTE" },
  { value: "SAMUNDRI", label: "SAMUNDRI" },
  { value: "SANGHAR", label: "SANGHAR" },
  { value: "SANGLA HILL", label: "SANGLA HILL" },
  { value: "SANGWALA", label: "SANGWALA" },
  { value: "SANJHORO", label: "SANJHORO" },
  { value: "SANJWAL", label: "SANJWAL" },
  { value: "SARAI ALAMGIR", label: "SARAI ALAMGIR" },
  { value: "Sarai Mughal", label: "Sarai Mughal" },
  { value: "SARAYE NORANG", label: "SARAYE NORANG" },
  { value: "SARDAR GARH", label: "SARDAR GARH" },
  { value: "SARDARYAB", label: "SARDARYAB" },
  { value: "SARGODHA", label: "SARGODHA" },
  { value: "SARI ALAMGIR", label: "SARI ALAMGIR" },
  { value: "SAROBA", label: "SAROBA" },
  { value: "SAROKI CHEEMA", label: "SAROKI CHEEMA" },
  { value: "SATRAH", label: "SATRAH" },
  { value: "SATYYANA", label: "SATYYANA" },
  { value: "SAUWAL", label: "SAUWAL" },
  { value: "SAWABI", label: "SAWABI" },
  { value: "SAWARI", label: "SAWARI" },
  { value: "SAWNI", label: "SAWNI" },
  { value: "SEHR BAGLA", label: "SEHR BAGLA" },
  { value: "SEHWAN SHARIF", label: "SEHWAN SHARIF" },
  { value: "SERMIK", label: "SERMIK" },
  { value: "SETHARJA", label: "SETHARJA" },
  { value: "SHABQADAR", label: "SHABQADAR" },
  { value: "SHADAD KOT", label: "SHADAD KOT" },
  { value: "SHADAN LUND", label: "SHADAN LUND" },
  { value: "SHADIWAL", label: "SHADIWAL" },
  { value: "SHAH BAGH", label: "SHAH BAGH" },
  { value: "SHAH PUR CHAKAR", label: "SHAH PUR CHAKAR" },
  { value: "SHAHDAD PUR", label: "SHAHDAD PUR" },
  { value: "SHAHDADPUR", label: "SHAHDADPUR" },
  { value: "SHAHDARA TOWN", label: "SHAHDARA TOWN" },
  { value: "SHAHKOT", label: "SHAHKOT" },
  { value: "SHAHPUR JAHANIA", label: "SHAHPUR JAHANIA" },
  { value: "SHAHPUR SADDAR", label: "SHAHPUR SADDAR" },
  { value: "SHAKARGARH", label: "SHAKARGARH" },
  { value: "SHAKIRILA", label: "SHAKIRILA" },
  { value: "SHAM KOT", label: "SHAM KOT" },
  { value: "SHAMS ABAD", label: "SHAMS ABAD" },
  { value: "SHANGLA", label: "SHANGLA" },
  { value: "SHARAQPUR SHARIF", label: "SHARAQPUR SHARIF" },
  { value: "Sharif Medical City", label: "Sharif Medical City" },
  { value: "SHEEDO", label: "SHEEDO" },
  { value: "SHEIKHOO SUGAR MILLS", label: "SHEIKHOO SUGAR MILLS" },
  { value: "SHEIKHU CHAK", label: "SHEIKHU CHAK" },
  { value: "SHEIKHUPURA", label: "SHEIKHUPURA" },
  { value: "SHERGARH", label: "SHERGARH" },
  { value: "SHERINGAL", label: "SHERINGAL" },
  { value: "SHEWA ADDA", label: "SHEWA ADDA" },
  { value: "SHIGAR", label: "SHIGAR" },
  { value: "SHIKARPUR", label: "SHIKARPUR" },
  { value: "SHIMLA HILL", label: "SHIMLA HILL" },
  { value: "SHOKHDARA", label: "SHOKHDARA" },
  { value: "SHORKOT", label: "SHORKOT" },
  { value: "SHORKOT CANTONMENT", label: "SHORKOT CANTONMENT" },
  { value: "SHUJABAD", label: "SHUJABAD" },
  { value: "SIALKOT", label: "SIALKOT" },
  { value: "SIBI", label: "SIBI" },
  { value: "SIHALA", label: "SIHALA" },
  { value: "SIKANDARABAD", label: "SIKANDARABAD" },
  { value: "SILANWALI", label: "SILANWALI" },
  { value: "SINJHORO", label: "SINJHORO" },
  { value: "SIR SUBA SHAH", label: "SIR SUBA SHAH" },
  { value: "SIRAYE MUHAJIR", label: "SIRAYE MUHAJIR" },
  { value: "SIVIA", label: "SIVIA" },
  { value: "SKARDU", label: "SKARDU" },
  { value: "SMAAL IND ESTATE. DASKA", label: "SMAAL IND ESTATE. DASKA" },
  { value: "Sohawa", label: "Sohawa" },
  { value: "SOHAWA ONLY MAIN GT ROAD", label: "SOHAWA ONLY MAIN GT ROAD" },
  { value: "SOKAR", label: "SOKAR" },
  { value: "SUDHANOTI (AJK)", label: "SUDHANOTI (AJK)" },
  { value: "SUI", label: "SUI" },
  { value: "SUI TOWN", label: "SUI TOWN" },
  { value: "SUKHU CHAK", label: "SUKHU CHAK" },
  { value: "SUKKUR", label: "SUKKUR" },
  { value: "SUMBRIAL", label: "SUMBRIAL" },
  { value: "Sundar Industrial Estate", label: "Sundar Industrial Estate" },
  { value: "SUNDARAWAL", label: "SUNDARAWAL" },
  { value: "SUNDER ADDA", label: "SUNDER ADDA" },
  { value: "Surkhpur", label: "Surkhpur" },
  { value: "SWABI", label: "SWABI" },
  { value: "SWAT", label: "SWAT" },
  { value: "SYED WALA", label: "SYED WALA" },
  { value: "T.T SINGH", label: "T.T SINGH" },
  { value: "TAJA BARA", label: "TAJA BARA" },
  { value: "TAKHT-E-BHAI", label: "TAKHT-E-BHAI" },
  { value: "TAKHT-I-BAHI", label: "TAKHT-I-BAHI" },
  { value: "TALAGANG", label: "TALAGANG" },
  { value: "TALAGUNG", label: "TALAGUNG" },
  { value: "TALASH", label: "TALASH" },
  { value: "TALHAR", label: "TALHAR" },
  { value: "TALL", label: "TALL" },
  { value: "TALPUR WADA", label: "TALPUR WADA" },
  { value: "TALVANDI", label: "TALVANDI" },
  { value: "TAMMAN", label: "TAMMAN" },
  { value: "TANDLIAWALA", label: "TANDLIAWALA" },
  { value: "TANDO ADAM", label: "TANDO ADAM" },
  { value: "TANDO ALLAHYAR", label: "TANDO ALLAHYAR" },
  { value: "TANDO BAGO", label: "TANDO BAGO" },
  { value: "TANDO GHULAM ALI", label: "TANDO GHULAM ALI" },
  { value: "TANDO JAM", label: "TANDO JAM" },
  { value: "TANDO JAN MUHAMMAD", label: "TANDO JAN MUHAMMAD" },
  { value: "TANDO MOHD KHAN", label: "TANDO MOHD KHAN" },
  { value: "TANGI", label: "TANGI" },
  { value: "TANK", label: "TANK" },
  { value: "TARBELA DAM", label: "TARBELA DAM" },
  { value: "TARNOL", label: "TARNOL" },
  { value: "TAUNSA SHARIF", label: "TAUNSA SHARIF" },
  { value: "TAXILA", label: "TAXILA" },
  { value: "TAXLA", label: "TAXLA" },
  { value: "TEHI", label: "TEHI" },
  { value: "THARI MIRWAH", label: "THARI MIRWAH" },
  { value: "THATHA AMIR", label: "THATHA AMIR" },
  { value: "THATTA", label: "THATTA" },
  { value: "THEENG MORE (ALLAHABAD)", label: "THEENG MORE (ALLAHABAD)" },
  { value: "THOA MEHRAM KHAN", label: "THOA MEHRAM KHAN" },
  { value: "THOHA KHALSA", label: "THOHA KHALSA" },
  { value: "THUL", label: "THUL" },
  { value: "THUL HAMZA", label: "THUL HAMZA" },
  { value: "THULL", label: "THULL" },
  { value: "TIBBA SULTANPURA", label: "TIBBA SULTANPURA" },
  { value: "TIMARGARA", label: "TIMARGARA" },
  { value: "TIMARGARAH", label: "TIMARGARAH" },
  { value: "TIRAT", label: "TIRAT" },
  { value: "TOBA TEK SINGH", label: "TOBA TEK SINGH" },
  { value: "TOBAH", label: "TOBAH" },
  { value: "TOPA ADAM", label: "TOPA ADAM" },
  { value: "TOPI", label: "TOPI" },
  { value: "TOPI (GIK UNIVERSITY AREA ONLY)*", label: "TOPI (GIK UNIVERSITY AREA ONLY)*" },
  { value: "TORWARSAK", label: "TORWARSAK" },
  { value: "TRANDA MOHAMMAD PANAH", label: "TRANDA MOHAMMAD PANAH" },
  { value: "TRANDA SAWAY KHAN", label: "TRANDA SAWAY KHAN" },
  { value: "TRET", label: "TRET" },
  { value: "TULAMBA", label: "TULAMBA" },
  { value: "TURBAT", label: "TURBAT" },
  { value: "UBARO", label: "UBARO" },
  { value: "UBAURO", label: "UBAURO" },
  { value: "UCH SHRIF", label: "UCH SHRIF" },
  { value: "UGGOKE", label: "UGGOKE" },
  { value: "UMAR KOT", label: "UMAR KOT" },
  { value: "UMERKOT", label: "UMERKOT" },
  { value: "UPPER CHITRAL", label: "UPPER CHITRAL" },
  { value: "UPPER DIR", label: "UPPER DIR" },
  { value: "USHERI", label: "USHERI" },
  { value: "USTA MOHAMMAD", label: "USTA MOHAMMAD" },
  { value: "USTA MUHAMMAD", label: "USTA MUHAMMAD" },
  { value: "UTHAL", label: "UTHAL" },
  { value: "VEHARI", label: "VEHARI" },
  { value: "VERPAL CHATTHA", label: "VERPAL CHATTHA" },
  { value: "VILLAGE SIAL", label: "VILLAGE SIAL" },
  { value: "WADA MACHHI", label: "WADA MACHHI" },
  { value: "WAH CANTT", label: "WAH CANTT" },
  { value: "WAH CANTT.", label: "WAH CANTT." },
  { value: "WAHNDO", label: "WAHNDO" },
  { value: "WAHOVA", label: "WAHOVA" },
  { value: "WAN RAHDA RAM", label: "WAN RAHDA RAM" },
  { value: "WAPDA COLONY (AJK)", label: "WAPDA COLONY (AJK)" },
  { value: "WARBATTAN", label: "WARBATTAN" },
  { value: "WARRAICHAN WALA", label: "WARRAICHAN WALA" },
  { value: "WARYAM WALA", label: "WARYAM WALA" },
  { value: "WAZIR KE CHATTHA", label: "WAZIR KE CHATTHA" },
  { value: "WAZIRABAD", label: "WAZIRABAD" },
  { value: "WINDER", label: "WINDER" },
  { value: "YAKA GHUND", label: "YAKA GHUND" },
  { value: "YAZMAN", label: "YAZMAN" },
  { value: "ZAFARWAL", label: "ZAFARWAL" },
  { value: "ZAHIR PIR", label: "ZAHIR PIR" },
  { value: "ZHOB", label: "ZHOB" },
] as const;

export const CITY_VALUES = CITIES.map((c) => c.value);
